# Pulls Grafana Keycloak client secret from OCI Vault.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-secret
    creationPolicy: Owner
    template:
      data:
        admin-user: "admin"
  data:
    - secretKey: client-secret
      remoteRef:
        key: grafana-oidc-secret
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin-password
    - secretKey: google-client-id
      remoteRef:
        key: grafana-google-client-id
    - secretKey: google-client-secret
      remoteRef:
        key: grafana-google-client-secret
