---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-r2-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAbCrrf9314f7/hAJAyds1ffoKqWTNnvdTHUHDXHr07EnLYp8pTLMm/fvXZrgtkZpTyF8tJ+jlX0UjBukigi7buThaLEdzUoaCvz9ljOlJMKUBHK4h8U3nxFLmKe34lufcKDSL9+y+UlDrnHPzmfChzISRfWppb9isiej9r4BungaGd4M66XPRWiKkXUOMMwdgcnaMCcNhFpIUrgex9rKyWk3lQoDpFN56TIur9d3WqnmE19w/bgIWwpi09M8lRnAvijnnoDl4Ra5as8kMw8+1mCzKWcEhQrMV8D7+NEqzcex4TEwTEQ8NdvmILjLY8sHJYyEMd1Zi3eoBvkPAW9ML0C4qfTP80Gw5IQtxKtzV/7yowj0/XUeMSD99GGfdm5u0qF2kzHDJGqhL041Bni8W/AERrfQK/SnSAYTVxRvUvsbmKvUnXGJzeD0J9yN8j0Ky7cekXyoTyB6yhTJjppGzd3NVYolRAvVzj0Fk4iK6eosBbY86fenQLW0NrmNR8EjSISlQcD4HoGQzJdZbAR/Q9gXotNToMAk253mG0zrsWFPqPBkrk/YyxifVilyrZfC8EGneYKGHWrXw++0xxNQYG6goKB2qC8J9MY25OMsnPa2b6J0lfGw4MfbJM/WHiydmWFkG582B9XP997GElNGy6p066yQJHkaqxaz/mQL96fxNviVcAXS3WzsGxI1R227WD+x98NXc87e5vhsTaq8rN+E21Ouaga2mscz5n+E1mUJ0ImAVOUEjp7cxpFFMR8qnYGVdWYkTLN+bymbEG4ybez+5bR3WQYFyIHuQ2j+gTacC8n5gNsNHQiyE5omj0VfyAnDQY1huDF95KhQ9/zbGS1XTF2RLvEQ2yUSipVl5fqGCVKZtofNq1rsqxxNozvD9mBSq7Zl7NpA==
  template:
    metadata:
      creationTimestamp: null
      name: velero-r2-credentials
      namespace: velero
