apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    # Source 1: kube-prometheus-stack Helm chart
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 75.0.0
      helm:
        # Values file hamari git repo se
        valueFiles:
          - $git/apps/monitoring/values.yaml
    # Source 2: Hamari git repo (certificate + values)
    - repoURL: https://github.com/ShahzaibRao/oci-k3s-platform.git
      targetRevision: main
      ref: git
      path: apps/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # CRDs pehle install hon (prometheus-operator ke liye zaroori)
      - ServerSideApply=true
