---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAxiljJkBu1OM+VnwqA6rnT5sPJfPQBiu5/8gTP9kMeprSApxHHSGBWyp9535XDTpiT9RzbHcs6IHRwnXkXwa260wvRHtsTyTAjB1FXRpgmMSPQ1hw+zLaj2y9TwMIDQ70n4/x32HFTE909Hq0ssLlIDVjipKdmPIl49msh5olBRCF/1yUY+YPEzitsrlalN6VXu1JqZKtTqDqJBr6k7sRgR7qvNkkc3i1z7T9XR/JvFF7n72ed2LWCfv/lxIaQjReSB/OZw6vvozqPTsVX/ZDMGEDBMnTicQIsblZdSZheq5dKjiuBohE6lmDRo5xPPxrWhrSQZPoqPygFbbojB+dMMcVkmTyv05TsWcBXB2FVEcx1Eqr7TfcuVJF2XxQV1mdLq1FFeFakpi9QjfKvgsNINVawhgGMTn7O5sWk+vbVV+AgT8gV7r+fPoXCa7s+Q8giGJq+kSsA+bgxJb32AOcZiBq9PPfm2EUprAXfpUoMSnOw26G2FPIcXy+lE53gp0ERqP7houo04MADq7NtSiqd7+C0PHmgwvABrxjj35ijcJLIjDejd8S9qr/UfUsxDNsalb8xfwcmmBt7MPwa8QKijaMvKFDvy2VBXHUHf2bvrDz/hEQU7pd+hzBQShaOXyiNCbuylQsBY9a8k1IagEJMNvkowb8KQS+ZHW1JZ7EXIPAU9OEOxKJtYKvpSs3DELsQQcrlg1souh6uy9GPJZ7P73S6Evu5YEZi7MziKZnBcPuIP1bodMtLGO+dzMo/fsE0rdTniw==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
