apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-${DOMAIN_DASH}
  namespace: argocd
spec:
  secretName: wildcard-${DOMAIN_DASH}-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "*.${DOMAIN}"
    - "${DOMAIN}"
